"""Seed/demo data served when DATABASE_URL is not configured.

This allows the frontend to display realistic listings during local development
before the full Postgres stack is running.
"""

from __future__ import annotations

DEMO_LISTINGS: list[dict] = [
    {
        "reference_id": "Homes.bg:HBG-90210",
        "source_name": "Homes.bg",
        "owner_group": "Homes Media Group",
        "listing_url": "https://www.homes.bg/listing/demo-001",
        "external_id": "HBG-90210",
        "listing_intent": "sale",
        "property_category": "apartment",
        "city": "Sofia",
        "district": "Lozenets",
        "resort": None,
        "region": "Sofia-City",
        "address_text": "ul. Cherni Vrah 47",
        "latitude": 42.6781,
        "longitude": 23.3187,
        "area_sqm": 92,
        "rooms": 3,
        "price": 185000,
        "currency": "EUR",
        "description": "Bright 3-room apartment in Lozenets with south-facing balcony. Renovated 2024, Act 16 issued. Close to metro and parks.",
        "image_urls": [
            "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&h=500&fit=crop",
            "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&h=500&fit=crop",
        ],
        "first_seen": "2026-03-15T08:00:00Z",
        "last_seen": "2026-04-08T10:00:00Z",
        "last_changed_at": "2026-04-01T12:00:00Z",
        "removed_at": None,
        "parser_version": "homes_bg_v1",
        "crawl_provenance": {},
    },
    {
        "reference_id": "OLX.bg:OLX-44521",
        "source_name": "OLX.bg",
        "owner_group": "OLX Group",
        "listing_url": "https://www.olx.bg/listing/demo-002",
        "external_id": "OLX-44521",
        "listing_intent": "rent",
        "property_category": "apartment",
        "city": "Varna",
        "district": "Sea Garden",
        "resort": None,
        "region": "Varna",
        "address_text": "bul. Knyaz Boris I 65",
        "latitude": 43.2045,
        "longitude": 27.9115,
        "area_sqm": 38,
        "rooms": 1,
        "price": 450,
        "currency": "EUR",
        "description": "Cozy furnished studio 5 min walk from the beach. Sea view from the balcony. Available immediately.",
        "image_urls": [
            "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&h=500&fit=crop",
            "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&h=500&fit=crop",
        ],
        "first_seen": "2026-04-01T14:00:00Z",
        "last_seen": "2026-04-08T09:00:00Z",
        "last_changed_at": None,
        "removed_at": None,
        "parser_version": "olx_bg_v1",
        "crawl_provenance": {},
    },
    {
        "reference_id": "imot.bg:IMO-77881",
        "source_name": "imot.bg",
        "owner_group": None,
        "listing_url": "https://www.imot.bg/listing/demo-003",
        "external_id": "IMO-77881",
        "listing_intent": "sale",
        "property_category": "house",
        "city": "Bansko",
        "district": None,
        "resort": "Bansko",
        "region": "Blagoevgrad",
        "address_text": "near Pirin Golf",
        "latitude": 41.8366,
        "longitude": 23.4884,
        "area_sqm": 210,
        "rooms": 5,
        "price": 295000,
        "currency": "EUR",
        "description": "Detached house with mountain views near Pirin Golf & Country Club. 3 floors, garden, garage. Year-round access.",
        "image_urls": [
            "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800&h=500&fit=crop",
            "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&h=500&fit=crop",
        ],
        "first_seen": "2026-02-20T10:00:00Z",
        "last_seen": "2026-04-07T16:00:00Z",
        "last_changed_at": "2026-03-20T08:00:00Z",
        "removed_at": None,
        "parser_version": "imot_bg_v1",
        "crawl_provenance": {},
    },
    {
        "reference_id": "SUPRIMMO:SUP-12009",
        "source_name": "SUPRIMMO",
        "owner_group": "SUPRIMMO",
        "listing_url": "https://www.suprimmo.net/listing/demo-004",
        "external_id": "SUP-12009",
        "listing_intent": "sale",
        "property_category": "apartment",
        "city": "Burgas",
        "district": "Sarafovo",
        "resort": None,
        "region": "Burgas",
        "address_text": "Sarafovo beachside",
        "latitude": 42.5588,
        "longitude": 27.5235,
        "area_sqm": 68,
        "rooms": 2,
        "price": 89000,
        "currency": "EUR",
        "description": "2-room apartment 200m from the beach in Sarafovo. Sea view, furnished, Act 16. Pool and parking included.",
        "image_urls": [
            "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&h=500&fit=crop",
            "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800&h=500&fit=crop",
        ],
        "first_seen": "2026-03-28T07:00:00Z",
        "last_seen": "2026-04-08T11:00:00Z",
        "last_changed_at": None,
        "removed_at": None,
        "parser_version": "suprimmo_v1",
        "crawl_provenance": {},
    },
    {
        "reference_id": "BulgarianProperties:BGPR-88201",
        "source_name": "BulgarianProperties",
        "owner_group": "Bulgarian Properties Ltd",
        "listing_url": "https://www.bulgarianproperties.com/listing/demo-006",
        "external_id": "BGPR-88201",
        "listing_intent": "sale",
        "property_category": "villa",
        "city": "Sozopol",
        "district": None,
        "resort": "Sozopol",
        "region": "Burgas",
        "address_text": "near Old Town Sozopol",
        "latitude": 42.4172,
        "longitude": 27.6946,
        "area_sqm": 180,
        "rooms": 4,
        "price": 340000,
        "currency": "EUR",
        "description": "Luxury villa with private pool and sea views near Sozopol Old Town. 4 bedrooms, landscaped garden, modern finishes.",
        "image_urls": [
            "https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800&h=500&fit=crop",
            "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&h=500&fit=crop",
            "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&h=500&fit=crop",
        ],
        "first_seen": "2026-03-10T12:00:00Z",
        "last_seen": "2026-04-08T07:00:00Z",
        "last_changed_at": "2026-03-25T14:00:00Z",
        "removed_at": None,
        "parser_version": "bulgarianproperties_v1",
        "crawl_provenance": {},
    },
    {
        "reference_id": "LUXIMMO:LUX-10455",
        "source_name": "LUXIMMO",
        "owner_group": "LUXIMMO Finest Real Estate",
        "listing_url": "https://www.luximmo.bg/listing/demo-008",
        "external_id": "LUX-10455",
        "listing_intent": "sale",
        "property_category": "apartment",
        "city": "Sofia",
        "district": "Boyana",
        "resort": None,
        "region": "Sofia-City",
        "address_text": "Boyana residential area",
        "latitude": 42.6465,
        "longitude": 23.2708,
        "area_sqm": 240,
        "rooms": 4,
        "price": 520000,
        "currency": "EUR",
        "description": "Panoramic penthouse in Boyana with Vitosha mountain views. 240 sqm, private terrace, 2 parking spots, concierge service.",
        "image_urls": [
            "https://images.unsplash.com/photo-1600607687644-aac4c3eac7f4?w=800&h=500&fit=crop",
            "https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?w=800&h=500&fit=crop",
        ],
        "first_seen": "2026-03-01T08:00:00Z",
        "last_seen": "2026-04-08T10:00:00Z",
        "last_changed_at": "2026-03-15T10:00:00Z",
        "removed_at": None,
        "parser_version": "luximmo_v1",
        "crawl_provenance": {},
    },
    {
        "reference_id": "imoti.net:IN-40091",
        "source_name": "imoti.net",
        "owner_group": None,
        "listing_url": "https://www.imoti.net/listing/demo-011",
        "external_id": "IN-40091",
        "listing_intent": "sale",
        "property_category": "apartment",
        "city": "Plovdiv",
        "district": "Kapana",
        "resort": None,
        "region": "Plovdiv",
        "address_text": "ul. Otets Paisiy 12",
        "latitude": 42.1487,
        "longitude": 24.7499,
        "area_sqm": 78,
        "rooms": 2,
        "price": 115000,
        "currency": "EUR",
        "description": "Renovated 2-bed apartment in Plovdiv's creative district Kapana. Walking distance to Old Town, cafes, and galleries.",
        "image_urls": [
            "https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=800&h=500&fit=crop",
        ],
        "first_seen": "2026-03-18T14:00:00Z",
        "last_seen": "2026-04-08T12:00:00Z",
        "last_changed_at": "2026-04-02T09:00:00Z",
        "removed_at": None,
        "parser_version": "imoti_net_v1",
        "crawl_provenance": {},
    },
    {
        "reference_id": "Address.bg:ADDR-55103",
        "source_name": "Address.bg",
        "owner_group": "Address Real Estate",
        "listing_url": "https://www.address.bg/listing/demo-005",
        "external_id": "ADDR-55103",
        "listing_intent": "rent",
        "property_category": "apartment",
        "city": "Sofia",
        "district": "Studentski Grad",
        "resort": None,
        "region": "Sofia-City",
        "address_text": "ul. Acad. Stefan Mladenov",
        "latitude": 42.6534,
        "longitude": 23.3466,
        "area_sqm": 55,
        "rooms": 2,
        "price": 550,
        "currency": "EUR",
        "description": "Fully furnished 2-room apartment near Sofia University. New building, underground parking available.",
        "image_urls": [
            "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?w=800&h=500&fit=crop",
        ],
        "first_seen": "2026-04-02T09:00:00Z",
        "last_seen": "2026-04-08T08:00:00Z",
        "last_changed_at": None,
        "removed_at": None,
        "parser_version": "address_bg_v1",
        "crawl_provenance": {},
    },
]


DEMO_PROPERTIES: list[dict] = [
    {
        "property_id": "prop_demo_001",
        "dedupe_key": "lozenets_cherni_vrah_92",
        "entity_type": "apartment",
        "canonical_title": "3-room apartment in Lozenets, Sofia",
        "canonical_description": "Bright 3-room apartment in Lozenets with south-facing balcony.",
        "canonical_address": "ul. Cherni Vrah 47",
        "canonical_city": "Sofia",
        "canonical_building_name": None,
        "latitude": 42.6781,
        "longitude": 23.3187,
        "confidence_score": 0.5,
        "review_status": "needs_review",
    },
    {
        "property_id": "prop_demo_002",
        "dedupe_key": "varna_sea_garden_38",
        "entity_type": "apartment",
        "canonical_title": "Studio in Sea Garden, Varna",
        "canonical_description": "Cozy furnished studio near the beach.",
        "canonical_address": "bul. Knyaz Boris I 65",
        "canonical_city": "Varna",
        "canonical_building_name": None,
        "latitude": 43.2045,
        "longitude": 27.9115,
        "confidence_score": 0.2,
        "review_status": "needs_review",
    },
    {
        "property_id": "prop_demo_003",
        "dedupe_key": "bansko_pirin_golf_210",
        "entity_type": "house",
        "canonical_title": "Detached house near Bansko",
        "canonical_description": "3-floor house with mountain views near Pirin Golf.",
        "canonical_address": "near Pirin Golf",
        "canonical_city": "Bansko",
        "canonical_building_name": None,
        "latitude": 41.8366,
        "longitude": 23.4884,
        "confidence_score": 0.2,
        "review_status": "needs_review",
    },
]
